---
apiVersion: v1
kind: Pod
metadata:
  name: connectivity-minion01-pod1
  labels:
    app: connectivity
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["top"]
    stdin: true
    tty: true
  - name: hostnames
    image: k8s.gcr.io/serve_hostname
  nodeSelector:
    kubernetes.io/hostname: minion01
---
apiVersion: v1
kind: Pod
metadata:
  name: connectivity-minion01-pod2
  labels:
    app: connectivity
    svc: minion01
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["top"]
    stdin: true
    tty: true
  - name: hostnames
    image: k8s.gcr.io/serve_hostname
  nodeSelector:
    kubernetes.io/hostname: minion01
---
apiVersion: v1
kind: Pod
metadata:
  name: connectivity-minion02-pod1
  labels:
    app: connectivity
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["top"]
    stdin: true
    tty: true
  - name: hostnames
    image: k8s.gcr.io/serve_hostname
  nodeSelector:
    kubernetes.io/hostname: minion02
---
apiVersion: v1
kind: Pod
metadata:
  name: connectivity-minion02-pod2
  labels:
    app: connectivity
    svc: minion02
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["top"]
    stdin: true
    tty: true
  - name: hostnames
    image: k8s.gcr.io/serve_hostname
  nodeSelector:
    kubernetes.io/hostname: minion02
---
apiVersion: v1
kind: Service
metadata:
  name: connectivity-minion01
  labels:
    app: connectivity
spec:
  type: NodePort
  selector:
    app: connectivity
    svc: minion01
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: connectivity-minion02
  labels:
    app: connectivity
spec:
  type: NodePort
  selector:
    app: connectivity
    svc: minion02
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 9376
