apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: NetworkChaining
metadata:
  name: scenarios-1
spec:
  # Add fields here
  chainType: "labels"
  routingSpec:
    namespace: "default"
    networkChain: "app=slb,dync-net1,app=ngfw,dync-net2,app=sdewan"
    left:
      podSelector:
        matchLabels:
          app: nginx
      namespaceSelector:
        matchLabels:
          app: nginx
    right:
      podSelector:
        matchLabels:
          app: busybox
      namespaceSelector:
        matchLabels:
          app: busybox
      route:
         dst: "<ipaddress>"
         gw: "<ipaddress>"

---

apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: NetworkChaining
metadata:
  name: scenario2
spec:
  # Add fields here
  chainType: "routing"
  routingSpec:
    namespace: "default"
    networkChain: "app=slb,dync-net1,app=web-proxy,dync-net2,app=vfw"
    left:
    - networkName: "left-pnetwork"
      gatewayIp: "172.30.10.2"
      subnet: "172.30.10.0/24"
    - networkName: "left2-pnetwork"
      gatewayIp: "172.30.50.2"
      subnet: "172.30.50.0/24"
    right:
    - networkName: "right-pnetwork"
      gatewayIp: "172.30.20.2"
      subnet: "172.30.20.0/24"
      route:
        dst: "<ipaddress>"
        gw: "<ipaddress>"
    - networkName: "right2-pnetwork"
      gatewayIp: "172.30.60.2"
      subnet: "172.30.60.0/24"
      route:
        dst: "<ipaddress>"
        gw: "<ipaddress>"

---
apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: NetworkChaining
metadata:
  name: scenario2
spec:
  # Add fields here
  chainType: "routing"
  routingSpec:
    namespace: "default"
    networkChain: "app=slb,dync-net1,app=web-proxy,dync-net2,app=vfw"
    left:
    podSelector:
      matchLabels:
        app: nginx
    namespaceSelector:
      matchLabels:
        app: nginx
    - networkName: "left-pnetwork"
      gatewayIp: "172.30.10.2"
      subnet: "172.30.10.0/24"
    - networkName: "left2-pnetwork"
      gatewayIp: "172.30.50.2"
      subnet: "172.30.50.0/24"
    right:
    - networkName: "right-pnetwork"
      gatewayIp: "172.30.20.2"
      subnet: "172.30.20.0/24"
      route:
        dst: "<ipaddress>"
        gw: "<ipaddress>"
    - networkName: "right2-pnetwork"
      gatewayIp: "172.30.60.2"
      subnet: "172.30.60.0/24"
      route:
        dst: "<ipaddress>"
        gw: "<ipaddress>"

---
apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: NetworkChaining
metadata:
  name: scenario2
spec:
  # Add fields here
  chainType: "routing"
  routingSpec:
    namespace: "default"
    networkChain: "app=slb,dync-net1,app=web-proxy,dync-net2,app=vfw"
    left:
    podSelector:
      matchLabels:
        app: nginx
    namespaceSelector:
      matchLabels:
        app: nginx
    - networkName: "left-pnetwork"
      gatewayIp: "172.30.10.2"
      subnet: "172.30.10.0/24"
    - networkName: "left2-pnetwork"
      gatewayIp: "172.30.50.2"
      subnet: "172.30.50.0/24"
    right:
    podSelector:
        matchLabels:
          app: busybox
      namespaceSelector:
        matchLabels:
          app: busybox
      route:
         dst: "<ipaddress>"
         gw: "<ipaddress>"
    - networkName: "right-pnetwork"
      gatewayIp: "172.30.20.2"
      subnet: "172.30.20.0/24"
      route:
        dst: "<ipaddress>"
        gw: "<ipaddress>"
    - networkName: "right2-pnetwork"
      gatewayIp: "172.30.60.2"
      subnet: "172.30.60.0/24"
      route:
        dst: "<ipaddress>"
        gw: "<ipaddress>"



    