apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sdn-network-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  version: v1
  scope: Namespaced
  names:
	plural: sdnetworkDefinitions
	singular: sdnetworkDefinition
	kind: sdnetworkDefinition
	shortNames:
	- sdn-net-def
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
             networktype:
              items:
                properties:
                  type:
                    type: string
            dns:
              properties:
                domain:
                  type: string
                nameservers:
                  items:
                    type: string
                  type: array
                options:
                  items:
                    type: string
                  type: array
                search:
                  items:
                    type: string
                  type: array
              type: object
            ipv4Subnets:
              items:
                properties:
                  excludeIps:
                    type: string
                  gateway:
                    type: string
                  name:
                    type: string
                  subnet:
                    type: string
                required:
                - name
                - subnet
                type: object
              type: array
            ipv6Subnets:
              items:
                properties:
                  excludeIps:
                    type: string
                  gateway:
                    type: string
                  name:
                    type: string
                  subnet:
                    type: string
                required:
                - name
                - subnet
                type: object
              type: array
            routes:
              items:
                properties:
                  dst:
                    type: string
                  gw:
                    type: string
                required:
                - dst
                type: object
              type: array
            configuration:
              items:
                properties:
                  bridge:
                    type: string
                  args:
                    type: string
            NodeSelector:
               type: string
            nodelabelList:
              items:
               properties:
                 type: string
          required:
          - controller
          - networktype
          - ipv4Subnets
          type: object
        status:
          properties:
            state:
              type: string
            nodes:
              items:
                type: string
              type: array
          required:
          - state
          type: object
    additionalPrinterColumns:
    - name: status
      type: string
      description: The network status show the status of network
      jsonPath: .spec.status
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
