apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: NetworkChaining
metadata:
  name: example-networkchaining
spec:
  # Add fields here
  chainType: "Routing"
  routingSpec:
    namespace: "default"
    networkChain: "app=slb,dync-net1,app=web-proxy,dync-net2,app=vfw"
    leftNetwork:
    - networkName: "left-pnetwork"
      gatewayIp: "172.30.10.2"
      subnet: "172.30.10.0/24"
      podSelector:
        matchLabels:
          app: nginx
      namespaceSelector:
        matchLabels:
          app: nginx
    - networkName: "left2-pnetwork"
      gatewayIp: "172.30.50.2"
      subnet: "172.30.50.0/24"
      podSelector:
        matchLabels:
          app: nginx
      namespaceSelector:
        matchLabels:
          app: nginx
    rightNetwork:
    - networkName: "right-pnetwork"
      gatewayIp: "172.30.20.2"
      subnet: "172.30.20.0/24"
      dst: "0.0.0.0"
      podSelector:
        matchLabels:
          app: sdewan
      namespaceSelector:
        matchLabels:
          app: sdewan
    - networkName: "right2-pnetwork"
      gatewayIp: "172.30.60.2"
      subnet: "172.30.60.0/24"
      dst: "172.30.60.4"
      podSelector:
        matchLabels:
          app: vnat
      namespaceSelector:
        matchLabels:
          app: vnat
