apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: Network
metadata:
  name: virtualnet1
  labels:
    net: virtualnet1
spec:
  cniType : ovn4nfv
  ipv4Subnets:
  - subnet: 172.30.10.0/24
    name: subnet1
    gateway: 172.30.10.1/24
---
apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: Network
metadata:
  name: dync-net1
  labels:
    net: dync-net1
spec:
  cniType : ovn4nfv
  ipv4Subnets:
  - subnet: 172.30.33.0/24
    name: subnet1
    gateway: 172.30.33.1/24
---
apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: Network
metadata:
  name: dync-net2
  labels:
    net: dync-net2
spec:
  cniType : ovn4nfv
  ipv4Subnets:
  - subnet: 172.30.44.0/24
    name: subnet1
    gateway: 172.30.44.1/24
---
apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: Network
metadata:
  name: virtualnet2
  labels:
    net: virtualnet2
spec:
  cniType : ovn4nfv
  ipv4Subnets:
  - subnet: 172.30.20.0/24
    name: subnet1
    gateway: 172.30.20.1/24

---
apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: NetworkChaining
metadata:
  name: scenarios-1
spec:
  # Add fields here
  chainType: "routing"
  routingSpec:
    namespace: "default"
    networkChain: "net=virtualnet1,app=slb,net=dync-net1,app=ngfw,net=dync-net2,app=sdewan, net=virtualnet2,"
    left:
      podSelector:
        matchLabels:
          app: nginx
      namespaceSelector:
        matchLabels:
          app: nginx
     networkrepresentator:
         gatewayip: "<ipaddress>"
         subnet: "<ipaddress>"
    right:
      podSelector:
        matchLabels:
          app: busybox
      namespaceSelector:
        matchLabels:
          app: busybox
      networkrepresentator:
         gatewayip: "<ipaddress>"
         subnet: "<ipaddress>"
