apiVersion: apps/v1
kind: Deployment
metadata:
  name: vr
  labels:
    app: vr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vr
  template:
    metadata:
      labels:
        app: vr
      annotations:
        k8s.v1.cni.cncf.io/networks: '[                                        
            { "name": "ovn4nfv-k8s-plugin",                                    
              "interface": "net1"                                              
            }]'
              k8s.plugin.opnfv.org/nfn-network: '{ "type": "ovn4nfv", "interface": [{ "name": "right2-pnetwork", "interface": "net2", "ipaddress": "172.30.60.3", "defaultGateway": "false"}]}'

    spec:
      containers:
      - name: vr
        image: rkamudhan/netshoot:v1.0
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
      nodeSelector:
        kubernetes.io/hostname: minion01
---
