//
// nfn.proto
//
// Example that implements push notification from grpc server to client
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.3
// source: internal/pkg/nfnNotify/proto/nfn.proto

package nfn

import (
	"github.com/akraino-edge-stack/icn-nodus/internal/pkg/bandwidth"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName string `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
}

func (x *SubscribeContext) Reset() {
	*x = SubscribeContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeContext) ProtoMessage() {}

func (x *SubscribeContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeContext.ProtoReflect.Descriptor instead.
func (*SubscribeContext) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeContext) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type Notification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CniType string `protobuf:"bytes,1,opt,name=cni_type,json=cniType,proto3" json:"cni_type,omitempty"`
	// Types that are assignable to Payload:
	//	*Notification_InSync
	//	*Notification_ProviderNwCreate
	//	*Notification_ProviderNwRemove
	//	*Notification_ContainterRtInsert
	//	*Notification_ContainterRtRemove
	//	*Notification_PodAddNetwork
	//	*Notification_PodDelNetwork
	Payload isNotification_Payload `protobuf_oneof:"payload"`
}

func (x *Notification) Reset() {
	*x = Notification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetCniType() string {
	if x != nil {
		return x.CniType
	}
	return ""
}

func (m *Notification) GetPayload() isNotification_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Notification) GetInSync() *InSync {
	if x, ok := x.GetPayload().(*Notification_InSync); ok {
		return x.InSync
	}
	return nil
}

func (x *Notification) GetProviderNwCreate() *ProviderNetworkCreate {
	if x, ok := x.GetPayload().(*Notification_ProviderNwCreate); ok {
		return x.ProviderNwCreate
	}
	return nil
}

func (x *Notification) GetProviderNwRemove() *ProviderNetworkRemove {
	if x, ok := x.GetPayload().(*Notification_ProviderNwRemove); ok {
		return x.ProviderNwRemove
	}
	return nil
}

func (x *Notification) GetContainterRtInsert() *ContainerRouteInsert {
	if x, ok := x.GetPayload().(*Notification_ContainterRtInsert); ok {
		return x.ContainterRtInsert
	}
	return nil
}

func (x *Notification) GetContainterRtRemove() *ContainerRouteRemove {
	if x, ok := x.GetPayload().(*Notification_ContainterRtRemove); ok {
		return x.ContainterRtRemove
	}
	return nil
}

func (x *Notification) GetPodAddNetwork() *PodAddNetwork {
	if x, ok := x.GetPayload().(*Notification_PodAddNetwork); ok {
		return x.PodAddNetwork
	}
	return nil
}

func (x *Notification) GetPodDelNetwork() *PodDelNetwork {
	if x, ok := x.GetPayload().(*Notification_PodDelNetwork); ok {
		return x.PodDelNetwork
	}
	return nil
}

type isNotification_Payload interface {
	isNotification_Payload()
}

type Notification_InSync struct {
	InSync *InSync `protobuf:"bytes,2,opt,name=in_sync,json=inSync,proto3,oneof"`
}

type Notification_ProviderNwCreate struct {
	ProviderNwCreate *ProviderNetworkCreate `protobuf:"bytes,3,opt,name=provider_nw_create,json=providerNwCreate,proto3,oneof"`
}

type Notification_ProviderNwRemove struct {
	ProviderNwRemove *ProviderNetworkRemove `protobuf:"bytes,4,opt,name=provider_nw_remove,json=providerNwRemove,proto3,oneof"`
}

type Notification_ContainterRtInsert struct {
	ContainterRtInsert *ContainerRouteInsert `protobuf:"bytes,5,opt,name=containter_rt_insert,json=containterRtInsert,proto3,oneof"`
}

type Notification_ContainterRtRemove struct {
	ContainterRtRemove *ContainerRouteRemove `protobuf:"bytes,6,opt,name=containter_rt_remove,json=containterRtRemove,proto3,oneof"`
}

type Notification_PodAddNetwork struct {
	PodAddNetwork *PodAddNetwork `protobuf:"bytes,7,opt,name=pod_add_network,json=podAddNetwork,proto3,oneof"`
}

type Notification_PodDelNetwork struct {
	PodDelNetwork *PodDelNetwork `protobuf:"bytes,8,opt,name=pod_del_network,json=podDelNetwork,proto3,oneof"`
}

func (*Notification_InSync) isNotification_Payload() {}

func (*Notification_ProviderNwCreate) isNotification_Payload() {}

func (*Notification_ProviderNwRemove) isNotification_Payload() {}

func (*Notification_ContainterRtInsert) isNotification_Payload() {}

func (*Notification_ContainterRtRemove) isNotification_Payload() {}

func (*Notification_PodAddNetwork) isNotification_Payload() {}

func (*Notification_PodDelNetwork) isNotification_Payload() {}

type ProviderNetworkCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderNwName string      `protobuf:"bytes,1,opt,name=provider_nw_name,json=providerNwName,proto3" json:"provider_nw_name,omitempty"`
	Vlan           *VlanInfo   `protobuf:"bytes,2,opt,name=vlan,proto3" json:"vlan,omitempty"`
	Direct         *DirectInfo `protobuf:"bytes,3,opt,name=direct,proto3" json:"direct,omitempty"` // Add other types supported here beyond vlan
}

func (x *ProviderNetworkCreate) Reset() {
	*x = ProviderNetworkCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderNetworkCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderNetworkCreate) ProtoMessage() {}

func (x *ProviderNetworkCreate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderNetworkCreate.ProtoReflect.Descriptor instead.
func (*ProviderNetworkCreate) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderNetworkCreate) GetProviderNwName() string {
	if x != nil {
		return x.ProviderNwName
	}
	return ""
}

func (x *ProviderNetworkCreate) GetVlan() *VlanInfo {
	if x != nil {
		return x.Vlan
	}
	return nil
}

func (x *ProviderNetworkCreate) GetDirect() *DirectInfo {
	if x != nil {
		return x.Direct
	}
	return nil
}

type ProviderNetworkRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderNwName     string `protobuf:"bytes,1,opt,name=provider_nw_name,json=providerNwName,proto3" json:"provider_nw_name,omitempty"`
	VlanLogicalIntf    string `protobuf:"bytes,2,opt,name=vlan_logical_intf,json=vlanLogicalIntf,proto3" json:"vlan_logical_intf,omitempty"`
	DirectProviderIntf string `protobuf:"bytes,3,opt,name=direct_provider_intf,json=directProviderIntf,proto3" json:"direct_provider_intf,omitempty"` // Add other types supported here
}

func (x *ProviderNetworkRemove) Reset() {
	*x = ProviderNetworkRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProviderNetworkRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderNetworkRemove) ProtoMessage() {}

func (x *ProviderNetworkRemove) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderNetworkRemove.ProtoReflect.Descriptor instead.
func (*ProviderNetworkRemove) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderNetworkRemove) GetProviderNwName() string {
	if x != nil {
		return x.ProviderNwName
	}
	return ""
}

func (x *ProviderNetworkRemove) GetVlanLogicalIntf() string {
	if x != nil {
		return x.VlanLogicalIntf
	}
	return ""
}

func (x *ProviderNetworkRemove) GetDirectProviderIntf() string {
	if x != nil {
		return x.DirectProviderIntf
	}
	return ""
}

type VlanInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VlanId       string `protobuf:"bytes,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	ProviderIntf string `protobuf:"bytes,2,opt,name=provider_intf,json=providerIntf,proto3" json:"provider_intf,omitempty"`
	LogicalIntf  string `protobuf:"bytes,3,opt,name=logical_intf,json=logicalIntf,proto3" json:"logical_intf,omitempty"`
}

func (x *VlanInfo) Reset() {
	*x = VlanInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VlanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VlanInfo) ProtoMessage() {}

func (x *VlanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VlanInfo.ProtoReflect.Descriptor instead.
func (*VlanInfo) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{4}
}

func (x *VlanInfo) GetVlanId() string {
	if x != nil {
		return x.VlanId
	}
	return ""
}

func (x *VlanInfo) GetProviderIntf() string {
	if x != nil {
		return x.ProviderIntf
	}
	return ""
}

func (x *VlanInfo) GetLogicalIntf() string {
	if x != nil {
		return x.LogicalIntf
	}
	return ""
}

type DirectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProviderIntf string `protobuf:"bytes,1,opt,name=provider_intf,json=providerIntf,proto3" json:"provider_intf,omitempty"`
}

func (x *DirectInfo) Reset() {
	*x = DirectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectInfo) ProtoMessage() {}

func (x *DirectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectInfo.ProtoReflect.Descriptor instead.
func (*DirectInfo) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{5}
}

func (x *DirectInfo) GetProviderIntf() string {
	if x != nil {
		return x.ProviderIntf
	}
	return ""
}

type RouteData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dst string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Gw  string `protobuf:"bytes,3,opt,name=gw,proto3" json:"gw,omitempty"`
}

func (x *RouteData) Reset() {
	*x = RouteData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteData) ProtoMessage() {}

func (x *RouteData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteData.ProtoReflect.Descriptor instead.
func (*RouteData) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{6}
}

func (x *RouteData) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *RouteData) GetGw() string {
	if x != nil {
		return x.Gw
	}
	return ""
}

type ContainerRouteInsert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId string       `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Route       []*RouteData `protobuf:"bytes,2,rep,name=route,proto3" json:"route,omitempty"`
}

func (x *ContainerRouteInsert) Reset() {
	*x = ContainerRouteInsert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerRouteInsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRouteInsert) ProtoMessage() {}

func (x *ContainerRouteInsert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRouteInsert.ProtoReflect.Descriptor instead.
func (*ContainerRouteInsert) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerRouteInsert) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerRouteInsert) GetRoute() []*RouteData {
	if x != nil {
		return x.Route
	}
	return nil
}

type ContainerRouteRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId string       `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Route       []*RouteData `protobuf:"bytes,2,rep,name=route,proto3" json:"route,omitempty"`
}

func (x *ContainerRouteRemove) Reset() {
	*x = ContainerRouteRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerRouteRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRouteRemove) ProtoMessage() {}

func (x *ContainerRouteRemove) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRouteRemove.ProtoReflect.Descriptor instead.
func (*ContainerRouteRemove) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerRouteRemove) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerRouteRemove) GetRoute() []*RouteData {
	if x != nil {
		return x.Route
	}
	return nil
}

type PodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string              `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bandwidth bandwidth.Bandwidth `protobuf:"bytes,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{9}
}

func (x *PodInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NetConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *NetConf) Reset() {
	*x = NetConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetConf) ProtoMessage() {}

func (x *NetConf) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetConf.ProtoReflect.Descriptor instead.
func (*NetConf) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{10}
}

func (x *NetConf) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PodAddNetwork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId string       `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Pod         *PodInfo     `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Net         *NetConf     `protobuf:"bytes,3,opt,name=net,proto3" json:"net,omitempty"`
	Route       []*RouteData `protobuf:"bytes,4,rep,name=route,proto3" json:"route,omitempty"`
}

func (x *PodAddNetwork) Reset() {
	*x = PodAddNetwork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodAddNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodAddNetwork) ProtoMessage() {}

func (x *PodAddNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodAddNetwork.ProtoReflect.Descriptor instead.
func (*PodAddNetwork) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{11}
}

func (x *PodAddNetwork) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *PodAddNetwork) GetPod() *PodInfo {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *PodAddNetwork) GetNet() *NetConf {
	if x != nil {
		return x.Net
	}
	return nil
}

func (x *PodAddNetwork) GetRoute() []*RouteData {
	if x != nil {
		return x.Route
	}
	return nil
}

type PodDelNetwork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId string       `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Pod         *PodInfo     `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Net         *NetConf     `protobuf:"bytes,3,opt,name=net,proto3" json:"net,omitempty"`
	Route       []*RouteData `protobuf:"bytes,4,rep,name=route,proto3" json:"route,omitempty"`
}

func (x *PodDelNetwork) Reset() {
	*x = PodDelNetwork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodDelNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodDelNetwork) ProtoMessage() {}

func (x *PodDelNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodDelNetwork.ProtoReflect.Descriptor instead.
func (*PodDelNetwork) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{12}
}

func (x *PodDelNetwork) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *PodDelNetwork) GetPod() *PodInfo {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *PodDelNetwork) GetNet() *NetConf {
	if x != nil {
		return x.Net
	}
	return nil
}

func (x *PodDelNetwork) GetRoute() []*RouteData {
	if x != nil {
		return x.Route
	}
	return nil
}

type InSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeIntfIpAddress   string `protobuf:"bytes,1,opt,name=node_intf_ip_address,json=nodeIntfIpAddress,proto3" json:"node_intf_ip_address,omitempty"`
	NodeIntfMacAddress  string `protobuf:"bytes,2,opt,name=node_intf_mac_address,json=nodeIntfMacAddress,proto3" json:"node_intf_mac_address,omitempty"`
	NodeIntfIpv6Address string `protobuf:"bytes,3,opt,name=node_intf_ipv6_address,json=nodeIntfIpv6Address,proto3" json:"node_intf_ipv6_address,omitempty"`
}

func (x *InSync) Reset() {
	*x = InSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InSync) ProtoMessage() {}

func (x *InSync) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InSync.ProtoReflect.Descriptor instead.
func (*InSync) Descriptor() ([]byte, []int) {
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP(), []int{13}
}

func (x *InSync) GetNodeIntfIpAddress() string {
	if x != nil {
		return x.NodeIntfIpAddress
	}
	return ""
}

func (x *InSync) GetNodeIntfMacAddress() string {
	if x != nil {
		return x.NodeIntfMacAddress
	}
	return ""
}

func (x *InSync) GetNodeIntfIpv6Address() string {
	if x != nil {
		return x.NodeIntfIpv6Address
	}
	return ""
}

var File_internal_pkg_nfnNotify_proto_nfn_proto protoreflect.FileDescriptor

var file_internal_pkg_nfnNotify_proto_nfn_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6e,
	0x66, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e,
	0x66, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xf2, 0x03, 0x0a, 0x0c, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6e,
	0x69, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6e,
	0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x69, 0x6e, 0x5f, 0x73, 0x79, 0x6e, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x49, 0x6e, 0x53, 0x79, 0x6e, 0x63, 0x48,
	0x00, 0x52, 0x06, 0x69, 0x6e, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x46, 0x0a, 0x12, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x77, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x10, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x77, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x46, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x77,
	0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x00, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x4e, 0x77, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x49, 0x0a, 0x14, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x48, 0x00,
	0x52, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x74, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x12, 0x49, 0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x5f, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x48, 0x00, 0x52, 0x12, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12,
	0x38, 0x0a, 0x0f, 0x70, 0x6f, 0x64, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x6f, 0x64, 0x41, 0x64,
	0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x6f, 0x64, 0x41,
	0x64, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x38, 0x0a, 0x0f, 0x70, 0x6f, 0x64,
	0x5f, 0x64, 0x65, 0x6c, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x6f, 0x64, 0x44, 0x65, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x6f, 0x64, 0x44, 0x65, 0x6c, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x85,
	0x01, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x77, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x77, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x56, 0x6c, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x76, 0x6c, 0x61,
	0x6e, 0x12, 0x23, 0x0a, 0x06, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x12, 0x28, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x77, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x4e, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x76, 0x6c,
	0x61, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x74, 0x66, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x76, 0x6c, 0x61, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x63,
	0x61, 0x6c, 0x49, 0x6e, 0x74, 0x66, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x66, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x66, 0x22, 0x6b, 0x0a, 0x08, 0x56, 0x6c, 0x61, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x66, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x6e,
	0x74, 0x66, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x69, 0x6e,
	0x74, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61,
	0x6c, 0x49, 0x6e, 0x74, 0x66, 0x22, 0x31, 0x0a, 0x0a, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x6e, 0x74, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x66, 0x22, 0x2d, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x67, 0x77, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x67, 0x77, 0x22, 0x5b, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x22, 0x5b, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x22, 0x3b, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1d,
	0x0a, 0x07, 0x4e, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8c, 0x01,
	0x0a, 0x0d, 0x50, 0x6f, 0x64, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x03, 0x70, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x70, 0x6f, 0x64, 0x12, 0x1a,
	0x0a, 0x03, 0x6e, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4e, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x8c, 0x01, 0x0a,
	0x0d, 0x50, 0x6f, 0x64, 0x44, 0x65, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x03, 0x70, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x70, 0x6f, 0x64, 0x12, 0x1a, 0x0a,
	0x03, 0x6e, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4e, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x52, 0x03, 0x6e, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x06,
	0x49, 0x6e, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x2f, 0x0a, 0x14, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69,
	0x6e, 0x74, 0x66, 0x5f, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x74, 0x66, 0x49, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x31, 0x0a, 0x15, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x6e, 0x74, 0x66, 0x5f, 0x6d, 0x61, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x74, 0x66,
	0x4d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x33, 0x0a, 0x16, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x66, 0x5f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x6e, 0x74, 0x66, 0x49, 0x70, 0x76, 0x36, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32,
	0x3c, 0x0a, 0x09, 0x6e, 0x66, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x2f, 0x0a, 0x09,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x11, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x0d, 0x2e, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x30, 0x01, 0x42, 0x3a, 0x5a,
	0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x72, 0x61,
	0x69, 0x6e, 0x6f, 0x2d, 0x65, 0x64, 0x67, 0x65, 0x2d, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2f, 0x69,
	0x63, 0x6e, 0x2d, 0x6e, 0x6f, 0x64, 0x75, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x66, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescOnce sync.Once
	file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescData = file_internal_pkg_nfnNotify_proto_nfn_proto_rawDesc
)

func file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescGZIP() []byte {
	file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescOnce.Do(func() {
		file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescData)
	})
	return file_internal_pkg_nfnNotify_proto_nfn_proto_rawDescData
}

var file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_pkg_nfnNotify_proto_nfn_proto_goTypes = []interface{}{
	(*SubscribeContext)(nil),      // 0: SubscribeContext
	(*Notification)(nil),          // 1: Notification
	(*ProviderNetworkCreate)(nil), // 2: ProviderNetworkCreate
	(*ProviderNetworkRemove)(nil), // 3: ProviderNetworkRemove
	(*VlanInfo)(nil),              // 4: VlanInfo
	(*DirectInfo)(nil),            // 5: DirectInfo
	(*RouteData)(nil),             // 6: RouteData
	(*ContainerRouteInsert)(nil),  // 7: ContainerRouteInsert
	(*ContainerRouteRemove)(nil),  // 8: ContainerRouteRemove
	(*PodInfo)(nil),               // 9: PodInfo
	(*NetConf)(nil),               // 10: NetConf
	(*PodAddNetwork)(nil),         // 11: PodAddNetwork
	(*PodDelNetwork)(nil),         // 12: PodDelNetwork
	(*InSync)(nil),                // 13: InSync
}
var file_internal_pkg_nfnNotify_proto_nfn_proto_depIdxs = []int32{
	13, // 0: Notification.in_sync:type_name -> InSync
	2,  // 1: Notification.provider_nw_create:type_name -> ProviderNetworkCreate
	3,  // 2: Notification.provider_nw_remove:type_name -> ProviderNetworkRemove
	7,  // 3: Notification.containter_rt_insert:type_name -> ContainerRouteInsert
	8,  // 4: Notification.containter_rt_remove:type_name -> ContainerRouteRemove
	11, // 5: Notification.pod_add_network:type_name -> PodAddNetwork
	12, // 6: Notification.pod_del_network:type_name -> PodDelNetwork
	4,  // 7: ProviderNetworkCreate.vlan:type_name -> VlanInfo
	5,  // 8: ProviderNetworkCreate.direct:type_name -> DirectInfo
	6,  // 9: ContainerRouteInsert.route:type_name -> RouteData
	6,  // 10: ContainerRouteRemove.route:type_name -> RouteData
	9,  // 11: PodAddNetwork.pod:type_name -> PodInfo
	10, // 12: PodAddNetwork.net:type_name -> NetConf
	6,  // 13: PodAddNetwork.route:type_name -> RouteData
	9,  // 14: PodDelNetwork.pod:type_name -> PodInfo
	10, // 15: PodDelNetwork.net:type_name -> NetConf
	6,  // 16: PodDelNetwork.route:type_name -> RouteData
	0,  // 17: nfnNotify.Subscribe:input_type -> SubscribeContext
	1,  // 18: nfnNotify.Subscribe:output_type -> Notification
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_pkg_nfnNotify_proto_nfn_proto_init() }
func file_internal_pkg_nfnNotify_proto_nfn_proto_init() {
	if File_internal_pkg_nfnNotify_proto_nfn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderNetworkCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProviderNetworkRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VlanInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerRouteInsert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerRouteRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodAddNetwork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodDelNetwork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Notification_InSync)(nil),
		(*Notification_ProviderNwCreate)(nil),
		(*Notification_ProviderNwRemove)(nil),
		(*Notification_ContainterRtInsert)(nil),
		(*Notification_ContainterRtRemove)(nil),
		(*Notification_PodAddNetwork)(nil),
		(*Notification_PodDelNetwork)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pkg_nfnNotify_proto_nfn_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_nfnNotify_proto_nfn_proto_goTypes,
		DependencyIndexes: file_internal_pkg_nfnNotify_proto_nfn_proto_depIdxs,
		MessageInfos:      file_internal_pkg_nfnNotify_proto_nfn_proto_msgTypes,
	}.Build()
	File_internal_pkg_nfnNotify_proto_nfn_proto = out.File
	file_internal_pkg_nfnNotify_proto_nfn_proto_rawDesc = nil
	file_internal_pkg_nfnNotify_proto_nfn_proto_goTypes = nil
	file_internal_pkg_nfnNotify_proto_nfn_proto_depIdxs = nil
}
