apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkchainings.k8s.plugin.opnfv.org
spec:
  group: k8s.plugin.opnfv.org
  names:
    kind: NetworkChaining
    listKind: NetworkChainingList
    plural: networkchainings
    singular: networkchaining
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: NetworkChaining is the Schema for the networkchainings API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: NetworkChainingSpec defines the desired state of NetworkChaining
              properties:
                chainType:
                  type: string
                routingSpec:
                  properties:
                    leftNetwork:
                      items:
                        properties:
                          gatewayIp:
                            type: string
                          networkName:
                            type: string
                        required:
                          - gatewayIp
                          - networkName
                        type: object
                      type: array
                    namespace:
                      type: string
                    networkChain:
                      type: string
                    rightNetwork:
                      items:
                        properties:
                          gatewayIp:
                            type: string
                          networkName:
                            type: string
                        required:
                          - gatewayIp
                          - networkName
                        type: object
                      type: array
                  required:
                    - left
                    - namespace
                    - networkChain
                    - right
                  type: object
              required:
                - chainType
                - routingSpec
              type: object
            status:
              description: NetworkChainingStatus defines the observed state of NetworkChaining
              properties:
                state:
                  type: string
              required:
                - state
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
