apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nodus-root-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nodus-root-cert
  namespace: kube-system
spec:
  commonName: "nodus"
  duration: 17520h
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: nodus-root-issuer
  secretName: nodus-root-cert

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nodus-issuer
  namespace: kube-system
spec:
  ca:
    secretName: nodus-root-cert
