apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngfw
  labels:
    app.kubernetes.io/name: ngfw
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ngfw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ngfw
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "ovn4nfv-k8s-plugin",
              "interface": "net1"
            }]'
        k8s.plugin.opnfv.org/nfn-network: '{ "type": "ovn4nfv", "interface": [{ "name": "virtual-net1", "interface": "net2", "defaultGateway": "false"}, { "name": "virtual-net2", "interface": "net3", "defaultGateway": "false"}]}'

    spec:
      containers:
      - name: ngfw
        image: rkamudhan/netshoot:v1.0
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
---
