apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-left-deployment
  namespace: sfc-head
  labels:
    sfc: head
spec:
  replicas: 3
  selector:
    matchLabels:
      sfc: head
  template:
    metadata:
      labels:
        sfc: head

    spec:
      containers:
      - name: nginx
        image: rkamudhan/netshoot:v1.0
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
